config/routes.rb
SurveyApp::Application.routes.draw do

  root to: 'static_pages#home'
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/tour", to: "static_pages#tour"

  devise_for :users
  get "/mysurveys", to: "users#show", as: "user_surveys"

  get "/review_surveys", to: "users#review_surveys", as: "review_surveys"
  match "/save_surveys", to: "users#save_surveys", as: "save_surveys", via: 'post'

  resources :surveys do
    get "/sec/:index", to: "survey_sections#show", as: :section
    match "/sec/:index", to: "survey_sections#destroy", via: 'delete'
    match "/sec/:index", to: "survey_sections#update", via: 'put'
    
    get "/edit/:index", to: "surveys#edit", as: :edit_section
   
    get "/stats", to: "surveys#stats", as: :stats

    get "/getdata", to: "surveys#getdata"

    match "/new_section", to: "survey_sections#new", as: :new_section, via: "post"
    
    match "/sec/:index/submit", to: 'survey_sections#answer', via: 'post', as: :answer
    get "/finish", to: 'surveys#finish', via: 'get', as: :completed
    
    resources :charts
  end

  resources :questions, only: [:create, :update, :destroy]

  resources :campaigns do 
    resources :campaign_surveys, only: [:destroy], shallow: true
    resources :participants, only: [:index]  do
      collection do 
        get "add"
        match "edit", via: :post
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_authorization_check

  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def tour
  	if !current_user.nil?
  		sign_out current_user
  	end
  	@user = User.find_by(email: "guest@example.com")
  	@user ||= User.create(name: "Guest", email: "guest@example.com", password: "password");
  	sign_in @user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>


<h1>About Us</h1>
<p>This will contain the information about us.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>


<h1>Contact</h1>
<p>This will contain the contact details for the site.</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>


<h1>Help page</h1>
<p>This will have the documentation helping users to use the website.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>PsychInsight</h1>
<p class="lead"> Making scientific research and evaluations efficient, <br> enjoyable, and accessible to everyone.</p>
<br>
<div class="row" id="call-to-actions">
<% if user_signed_in? and current_user.is_creator? %>
	<div class="col-md-3 col-md-offset-3">
	    <%= link_to new_survey_path, class: "link-primary" do %>
	    <%= image_tag "survey-icon.png", width: "140px"  %>
	    <h2>Create a <br> New Survey</h2>
	    <% end %>
	</div>
	<div class="col-md-3">
	    <%= link_to campaigns_path, class: "link-secondary" do %>
	    <%= image_tag "campaign-icon.png", width: "140px"  %>
	    <h2>Manage Campaigns</h2>
	    <% end %>
	</div>
	<div class="col-md-3"></div>
	</div>
<% else %>
	<div class="col-md-4 col-md-offset-4">
	    <%= link_to surveys_path, class: "link-primary" do %>
	    <%= image_tag "survey-icon.png", width: "140px"  %>
	    <h2>Browse Surveys</h2>
	    <% end %>
	</div>
	<div class="col-md-4"></div>
	</div>

<% end %>
</div>

<%#<footer><small>Disclaimer: This is a work in progress prototype used to give an idea of the kind of functionality we can provide. </small></footer>%>

app/views/static_pages/tour.html.erb
<% provide(:title, 'Tour') %>

<div class="row">
<div class="col-md-offset-1 col-md-10">

<div class="page-header">
<h2>PsychInsight Tour <br><small>Welcome to PsychInsight. <br>This page will give a tour through the main features of PsychInsight's survey application.</small></h2>

<p>
For your convenience, a guest user account has been created for you. <br>
If you want to try logging in and out, the username is <mark>guest@example.com</mark> and the password is <mark>password</mark>.
</p>
</div>

<h3>Features to try:</h3>

<div class="list-group">
<%= link_to "Create a new survey", new_survey_path, class: "list-group-item" %>
<%= link_to "Answer a survey", survey_path(Survey.first), class: "list-group-item" %>
<%= link_to "View created and answered surveys", user_surveys_path, class: "list-group-item" %>
<%= link_to "View survey stats", survey_stats_path(Survey.first), class: "list-group-item" %>
<%= link_to "Create a campaign", new_campaign_path, class: "list-group-item" %>
<%= link_to "View campaigns", campaigns_path, class: "list-group-item" %>

</div>

</div>
</div>