config/routes.rb
SurveyApp::Application.routes.draw do

  root to: 'static_pages#home'
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/tour", to: "static_pages#tour"

  devise_for :users
  get "/mysurveys", to: "users#show", as: "user_surveys"

  get "/review_surveys", to: "users#review_surveys", as: "review_surveys"
  match "/save_surveys", to: "users#save_surveys", as: "save_surveys", via: 'post'

  resources :surveys do
    get "/sec/:index", to: "survey_sections#show", as: :section
    match "/sec/:index", to: "survey_sections#destroy", via: 'delete'
    match "/sec/:index", to: "survey_sections#update", via: 'put'
    
    get "/edit/:index", to: "surveys#edit", as: :edit_section
   
    get "/stats", to: "surveys#stats", as: :stats

    get "/getdata", to: "surveys#getdata"

    match "/new_section", to: "survey_sections#new", as: :new_section, via: "post"
    
    match "/sec/:index/submit", to: 'survey_sections#answer', via: 'post', as: :answer
    get "/finish", to: 'surveys#finish', via: 'get', as: :completed
    
    resources :charts
  end

  resources :questions, only: [:create, :update, :destroy]

  resources :campaigns do 
    resources :campaign_surveys, only: [:destroy], shallow: true
    resources :participants, only: [:index]  do
      collection do 
        get "add"
        match "edit", via: :post
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_paranoid
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save { self.email = email.downcase unless self.temporary 
                self.is_creator = true if !self.email.nil? and  self.email.ends_with? "psychinsight.co.uk"}

  before_destroy {self.surveys.destroy_all}

  has_many :answers, dependent: :destroy
  has_many :active_surveys, dependent: :destroy # surveys in progress/completed
  has_many :surveys, foreign_key: :owner_id # surveys owned by this user
  has_many :campaigns, foreign_key: :owner_id

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  with_options unless: :temporary do |user|
    user.validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
    user.validates :name, presence: true
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :index, :destroy]

#  before_action :signed_in_user, only: [:edit, :update, :index, :destroy]
#  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  skip_authorization_check

  def show
    @user = current_user
    @surveys = @user.surveys
    @active_surveys = @user.active_surveys.includes(:survey)
    if @user.nil?
      if !session[:guest_user_id].nil?
        @user = User.find(session[:guest_user_id])
      else
        flash[:alert] = "You need to be signed in to view surveys."
        redirect_to new_user_session_path
      end
    end
  end

  def review_surveys
    @user = current_user
    @guest_user = User.find(session[:guest_user_id])
  end

  def save_surveys
    # Logic to move surveys to new user
    @guest_user = User.find(session[:guest_user_id])

    if !params[:survey].nil?
      @guest_user.active_surveys.each do |as|
        if params[:survey][as.id.to_s] == "1"
          as.update(user_id: current_user.id)
          Answer.where(user_id: @guest_user.id).update_all(user_id: current_user.id)
        end
      end
    end

    session[:guest_user_id] = nil
    @guest_user.destroy
    
    redirect_to user_surveys_path
  end
  
  private
      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/review_surveys.html.erb
 <% provide(:title, "Review Surveys") %>

 <h3> You have unsaved surveys. Would you like to keep them? </h3>

 <%= form_tag "/save_surveys", action: "post", role: "form" do %>
 <fieldset>
 	
<% @guest_user.active_surveys.order(updated_at: :desc).each do |active_survey| %>
<ul class="list-group col-md-8">
		<% survey = active_survey.survey %>
		<li class="list-group-item list-group-item-#{active_survey.completed ? "success" : "info"}">
		<div class="list-group-item-header">
			<h2>
				<%= survey.name %>
			</h2>
		</div>
		<p class="list-group-item-text col-md-7">
			Completed: <%= t active_survey.completed.class %>
		</p>
		<div clas="col-md-1">
			<%= label_tag  "survey[#{active_survey.id}]", "Save survey to user account?" %>
			<%= check_box_tag "survey[#{active_survey.id}]"%>
		</div>
		</li>
</ul>
<% end %>

 </fieldset>

 <%= submit_tag "Continue", class: "btn btn-large btn-primary" %>


<% end %>

app/views/users/show.html.erb
<%= provide(:title, full_title("User Profile")) %>
<div class="row">
<div class="col-md-offset-1 col-md-10">

<div class="page-header">
<% if creator_user? %>
<h1>My Surveys <br><small>View surveys you own and surveys you answered.</small></h1>
<% else %>
<h1>My Surveys <br><small>View answered surveys.</small></h1>
<% end %>
</div>
<%= link_to "Create new survey", new_survey_path, class: "btn btn-primary" if creator_user?%>
<%= link_to "Browse surveys", surveys_path, class: "btn btn-success" %>
<br>

<hr>
<br>
<% if creator_user? %>
<h2>Created surveys</h2>
<% if @surveys.empty? %>
<div class="list-group">
	<div class="list-group-item center">
			<div class="list-group-item-header">
			<h2>
				You haven't created any surveys yet.
			</h2>
			</div>
			<div class="list-group-item-text">
			<br>
			<%= link_to "Create a new survey", new_survey_path, class: "btn btn-large btn-primary"  %>	
			<br>
			</div>
	</div>
</div>

<% end %>

<div class="list-group">
	<% @surveys.each do |survey| %>
		<div class="list-group-item">
		<div class="list-group-item-header">
			<h3>
				<div class="row">
				<div class="col-md-5">
				<b><%= survey.name %></b><br>
				<% if survey.is_public? %>
				<h4 class="text-success">Public</h4>
				<% else %>
				<h4 class="text-danger">Hidden</h4>
				<% end %>
				</div>
				<div class="col-md-2">
					<%= form_for survey do |f|  %>
					<%= f.hidden_field :is_public, value: !survey.is_public? %>
					<% button_text = survey.is_public? ? "Take Offline" : "Make Public" %>
					<% button_class = survey.is_public? ? "btn-danger" : "btn-success" %>
					<%= f.submit button_text, class: "btn btn-lg #{button_class}"  %>
					<% end %>
				</div>
				<div class="col-md-5">
					<%= link_to "Stats", survey_stats_path(survey), class: "btn btn-primary" %>
					<%= link_to "Edit", edit_survey_path(survey), class: "btn btn-success" %>
					<%= link_to "Charts", survey_charts_path(survey) , class: "btn btn-primary" %>
					<%= link_to "Delete", survey_path(survey), class: "btn btn-danger", method: 'delete', confirm: "Delete this survey?" %>
				</div>
				</div>
			</h3>
		</div>
		<p class="list-group-item-text">
		Number of responses: <%= ActiveSurvey.where(survey_id: survey.id, completed: true).count %>	
		</p>
		</div>
	<% end %>
</div>

<% end %>
<br>

<h2>Answered surveys</h2>
<% if @active_surveys.empty? %>
<div class="list-group">
	<div class="list-group-item center">
			<div class="list-group-item-header">
			<h3>
				You haven't answered any surveys yet.
			</h3>
			</div>
			<div class="list-group-item-text">
			<br>
			<%= link_to "Find a survey", surveys_path, class: "btn btn-lg btn-primary"  %>	
			<br>
			</div>
	</div>
</div>

<% end %>

<div class="list-group">
	<% @active_surveys.order(updated_at: :desc).each do |active_survey| %>
		<% survey = active_survey.survey %>
		<%= link_to survey_path(survey), class: "list-group-item list-group-item-#{active_survey.completed ? "success" : "info"}" do %>
		<div class="list-group-item-header">
			<h3>
				<b><%= survey.name %></b>
			</h3>
		</div>
		<p class="list-group-item-text">
			Completed: <%= t active_survey.completed.class %>
		</p>
		<% end %>
	<% end %>
</div>

</div>
</div>