config/routes.rb
SurveyApp::Application.routes.draw do

  root to: 'static_pages#home'
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/tour", to: "static_pages#tour"

  devise_for :users
  get "/mysurveys", to: "users#show", as: "user_surveys"

  get "/review_surveys", to: "users#review_surveys", as: "review_surveys"
  match "/save_surveys", to: "users#save_surveys", as: "save_surveys", via: 'post'

  resources :surveys do
    get "/sec/:index", to: "survey_sections#show", as: :section
    match "/sec/:index", to: "survey_sections#destroy", via: 'delete'
    match "/sec/:index", to: "survey_sections#update", via: 'put'
    
    get "/edit/:index", to: "surveys#edit", as: :edit_section
   
    get "/stats", to: "surveys#stats", as: :stats

    get "/getdata", to: "surveys#getdata"

    match "/new_section", to: "survey_sections#new", as: :new_section, via: "post"
    
    match "/sec/:index/submit", to: 'survey_sections#answer', via: 'post', as: :answer
    get "/finish", to: 'surveys#finish', via: 'get', as: :completed
    
    resources :charts
  end

  resources :questions, only: [:create, :update, :destroy]

  resources :campaigns do 
    resources :campaign_surveys, only: [:destroy], shallow: true
    resources :participants, only: [:index]  do
      collection do 
        get "add"
        match "edit", via: :post
      end
    end
  end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	acts_as_paranoid
	
	validates :name, presence: true
	has_many :sections, class_name: "SurveySection", dependent: :destroy, inverse_of: :survey
	has_many :survey_sections
	has_many :charts
	has_many :active_surveys, dependent: :destroy, inverse_of: :survey

	belongs_to :owner, class_name: "User"
	has_many :questions, through: :sections
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index, :finish]
  skip_authorization_check only: [:index, :finish]

  def show
  	@survey = Survey.find(params[:id])
    
    authorize! :read, @survey

    respond_to do |format|
      format.html {}
      format.json {render json: @survey}
    end
  end

  def index
    @surveys = Survey.accessible_by(current_ability).page(params[:page])
  end

  def finish
    survey = Survey.find(params[:survey_id])
    user = view_context.current_or_guest_user
    if user.nil?
      flash.now[:alert] = "No user found"
    end
    active_survey = ActiveSurvey.find_by(user_id: user, survey_id: params[:survey_id])
    required_qs = active_survey.survey.questions.where(required: true).pluck("questions.id")
    answered_qs = Answer.where(user_id: user.id, question_id: required_qs).pluck(:question_id)
    # Yup, this does exactly what it looks like
    missing_qs = required_qs - answered_qs
    if missing_qs.length > 0
      flash[:alert] = "Some required questions are missing." 
      idx = Question.find(missing_qs[0]).survey_section.idx
      redirect_to  survey_section_path(@survey, idx)
    else
      active_survey.update(completed: true)
    end
  end

  def new
    @survey = Survey.new
    authorize! :create, @survey
  end

  def create
  	survey = Survey.new(survey_params.merge( owner_id: current_user.id))
    authorize! :create, survey
    if survey.save
      flash[:notice] = "Survey Created"
       redirect_to edit_survey_path survey
    else
      flash.now[:fail] = "Error creating survey"
      render 'new'
    end
  end

  def edit
    id = params[:survey_id]
    id ||= params[:id]
  	@survey ||= Survey.find(id)

    @survey_sections = @survey.sections

    @questions = Question.where(survey_section_id: @survey_sections.ids)
                      .includes(:option_group, :question_type, :option_choices)
                      .group_by(&:survey_section_id)

    @types_map = QuestionType.all.order(:name).map{|type| [type.name.gsub("_"," ").capitalize, type.id]}

    authorize! :edit, @survey

    if params[:index].nil?
  	  @survey_section ||= @survey.sections.where(idx: 1).first
      if @survey_section.nil?
        @survey_section = @survey.sections.create(name: "Section 1", title: "New Section", idx: 1)
      end
    else
      @survey_section ||= @survey.sections.where(idx: params[:index]).first
    end
  end

  def update
    survey = Survey.find(params[:id])

    survey.assign_attributes(survey_params)

    authorize! :update, survey
    if survey.save
      flash[:success] = "Changed"
    else
      flash[:error] = "Could not change"
    end 

    redirect_to :back
  end

  #this is the function that deals with populating the previous question drop down boxes so that particiipants can choose 
  #to use answer options from a previous question. 
  def getdata
    
    #@survey = Survey.find(params[:survey_id])
    #@questions = Question.where(survey_section_id: @survey.sections.ids)
    #@answerOptions = 
    # this contains what has been selected in the first select box
    authorize! :post, @survey

    @data_from_select1 = params[:first_select]


    # we get the data for selectbox 2
    @data_for_select2 = @questions.where(:name => @data_from_select1).all

    # render an array in JSON containing arrays like:
    # [[:id1, :name1], [:id2, :name2]]
    respond_to do |format|
      format.html {}
      format.json {render :json => @data_for_select2.map{|c| [c.id, c.name]}}
    end
    
  end

  def stats
    @survey = Survey.find(params[:survey_id])
    @questions = Question.where(survey_section_id: @survey.sections.ids).includes(:question_type, :option_choices, :option_group)
    @ta_type = QuestionType.find_by(name: "text_area").id
    @answers = {}
    @answer_options
    
    authorize! :stats, @survey

    # Return all question ids for survey:
    qs = @questions.distinct.pluck("questions.id").sort
    # Return all user ids who have answered those questions:
    us = Answer.where(question_id: qs).distinct.pluck(:user_id).sort
    @users = us

    preload_answers = Answer.where(user_id: us, question_id: qs)
    grouped_answers = preload_answers.group_by(&:user_id)

    @answer_options = AnswerOption.where(answer_id: preload_answers.pluck(:id)).group_by(&:answer_id)

    #Get answers for each user
    us.each do |u| 
      @answers[u] = grouped_answers[u].index_by(&:question_id)
    end

    respond_to do |format|
      format.html
      format.csv { send_data answers_to_csv(@answers, qs)}
    end
  end

  def destroy
    @survey = Survey.find(params[:id])

    authorize! :destroy, @survey
    @survey.destroy

    flash[:info] = "Deleted #{@survey.name}." #" using params: #{params}."
    
    redirect_to user_surveys_path
  end

  private

  def survey_params
    params.require(:survey).permit(:name, :description, :is_public)
  end

  def answers_to_csv(answers, qs, options = {})
    CSV.generate(options) do |csv|
      csv << ["User"].concat(qs)
      answers.each do |uid, questions|
        csv << [uid].concat(qs.map {|qid| questions[qid].nil? ? "" : questions[qid].answer_options.pluck(:answer_text).join(' ') })
      end
    end
  end


end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_chart_select.html.erb
<div class="form-body">

<%= form_for(Chart.new) do |f| %>
	<fieldset>

	<%= f.label "Chart Type", class: "control-label" %>
	<% chartoptions = ChartType.pluck(:type_id) %>
	<%= f.select :type_id, options_for_select(chartoptions.map{|c| c.gsub("_"," ").capitalize}), {}, {class: "form-control",  id: "ChartSelect"} %>

	<%= f.label "Questions", class: "control-label" %>
	<% availableqs = @questions.all.map{|qname| [qname.name]} %>
	<%= f.select :question_id, options_for_select(availableqs), {}, {class: "form-control"} %>
	
	<div id="extra-question">
		<%= f.label "Questions", class: "control-label" %>
		<% availableqs = @questions.all.map{|qname| [qname.name]} %>
		<%= f.select :question_id2, options_for_select(availableqs), {}, {class: "form-control"} %>

	</div>
	
	</fieldset>
	<br>
	<div class="form-submit">
	<%= f.button "Make Graph", class: "btn btn-primary btn-large" %>
	</div>

<% end #f %>

app/views/surveys/_survey.html.erb
<%# Set active_survey to a new by default, unless can find a matching survey for the
current user. %>
<% active_survey = ActiveSurvey.new if current_or_guest_user.nil? %>
<% active_survey ||= current_or_guest_user.active_surveys.find_by(survey_id: survey.id) || ActiveSurvey.new %>
<%= link_to survey_path(survey), class: "list-group-item " +
"#{active_survey.completed ? "list-group-item-success" : "list-group-item-info" unless active_survey.new_record?}" do %>
<div class="list-group-item-header">
	<h3>
		<b><%= survey.name %></b>
	</h3>
</div>
<p class="list-group-item-text">
	<%= survey.description %>
	<% unless active_survey.new_record?  %>
	<br>
	<b><%= active_survey.completed? ? "Completed" : "In progress" %></b>
	<% end %>
</p>
<% end %>

app/views/surveys/chartcreate.html.erb
<%= provide(:title, @survey.name) %>
<%= javascript_include_tag "surveys" %>

<h1>Lets chart some data!</h1>

<div class="row">
<div class="col-sm-3" id="chart-options">
<legend>Choose a chart</legend>
<%= render partial: "surveys/chart_select", locals: {q: @questions.name, s: @survey} %> <!-- if q is set as @question.name then it works -->
</div>

<div class="col-sm-9" id="chart-display">
	<%= render partial: "questions/chartcreate", locals: {q: @chart} %>
</div>

</div>

app/views/surveys/edit.html.erb
<%= provide(:title, @survey.name) %>

<h1>Edit Survey</h1>

<div class="row">
<div class="col-md-3" id="survey-options">
<legend>Add Components</legend>
<%= render partial: "questions/edit_question", locals: {q: Question.new(survey_section: @survey_section)} %>
</div>

<div id="tabs" class="col-md-9">
	<ul class="nav nav-tabs">
		<% @survey.sections.each do |sec| %>
		<li <%= "class=active" if @survey_section == sec %>><a data-toggle="tab" href="#tabs-<%= sec.idx %>" sec="<%= sec.id %>"><%= sec.idx %></a></li>
		<% end %>
		<li role="presentation"> 
		<%= link_to survey_new_section_path(@survey), class: "btn", id: "add-section-tab", method: :post do %>
		<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
		<% end %>
		</li>
	</ul>

	<div class="tab-content">

	<% @survey_sections.each do |sec| %>
	<div id="tabs-<%= sec.idx %>" data-object="survey_section" data-url="<%= survey_section_path @survey, sec.idx %>" class="tab-pane well well-lg <%= "active" if @survey_section == sec %>">

	<legend>
	<div class="row">
	<div class="col-md-9">
	<%= best_in_place sec, :title, url: survey_section_path(@survey, sec.idx)
	# Add this line if we want a save button by the title.
	#, ok_button: "Save", ok_button_class: "btn btn-md btn-primary" 
	%>
	</div>
	<div class="col-md-3"><%= link_to "Delete", survey_section_path(@survey, sec.idx), method: 'delete', class: "btn btn-sm btn-danger"%></div></div></legend>

	<div class="row">
		<div class="col-md-9">
			<h4><%= best_in_place sec, :subtitle, :as => :textarea, :nil => "Click me to add a description of this survey section, this will be displayed to participants.", url: survey_section_path(@survey, sec.idx)
			# Add this line if we want a save button by the title.
			#, ok_button: "Save", ok_button_class: "btn btn-md btn-primary" 
			%></h4>
		</div>
	</div>
	<fieldset>
		<ul class="list-group">
		<% unless @questions[sec.id].nil? %>
		<% @questions[sec.id].each do |q| %>
			<span class="badge pull-right">
				<!-- Link to modal -->
				<%= link_to "Edit", "#", "data-toggle" => "modal", "data-target" => "#myModal#{q.id}" %>
				<%= link_to "Delete", q, method: "delete", class: "text-danger" %>
			</span>
			<%= render partial: "questions/edit", locals: {q: q} %> 
				<%= fields_for "answers[#{q.id}]", Answer.new do |f| %>
				<% f.object.answer_options.build %>
					<%= render partial: "survey_sections/question_types/#{q.question_type.name}", locals: { f: f, q: q, ans_options: f.object.answer_options}, layout: "survey_sections/question_types/question"  %>
				<% end %>
		<% end %>
		<% end %>
		</ul>
	
		<div class="form-actions">
		<%#= submit_tag "Submit answer", name: nil, class: 'btn btn-primary', disabled: true, title: "This is a preview."%>
		</div>
	</fieldset>	
	</div>
	<% end %>
	</div>

</div>

<div class="col-md-3">

</div>

</div>

app/views/surveys/finish.html.erb
<% provide(:title, "Survey Finished") %>

<h1>Survey Finished</h1>

Thank you!

<%= link_to "Back to all surveys", surveys_path %>

app/views/surveys/index.html.erb
<% provide(:title, 'All surveys') %>
<div class="row">
<div class="col-md-offset-1 col-md-10">


<div class="page-header">
<h1>All surveys <br><small>Browse possible surveys to answer</small></h1>
</div>
<%= paginate @surveys %>

<div class="list-group">
  <%= render @surveys %>
</div>

<%= paginate @surveys %>

</div>
</div>

app/views/surveys/new.html.erb
<%= provide(:title, "Create New") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @survey, role: "form", action: "post" do |f| %>
		<fieldset>
		
		<legend>Create a new survey</legend>
		
		<div class="form-group">
		<%= f.label :name, class: "control-label"%>
		<%= f.text_field :name, class: "form-control" %>
		</div>
		
		<div class="form-group">
		<%= f.label :description, class: "control-label" %>
		<%= f.text_area :description, class: "form-control" %>
		</div>

		<div class="checkbox">
		<%= f.label :is_public do %>
		<%= f.check_box :is_public %>
		Make this survey public
		<% end %>
		</div>

		<%= f.submit "Create", class: "btn btn-large btn-primary" %>

      </fieldset>

	<% end %>
  </div>
</div>

app/views/surveys/show.html.erb
<%= provide(:title, @survey.name) %>

<div class="center hero-unit">

<h1><%= @survey.name %></h1>
<h3><%= @survey.description %></h3>

<p>This survey has <%= pluralize(@survey.sections.count, "section") %>.</p>

<%= link_to "Start survey", survey_section_path(@survey, 1), class: "btn btn-large btn-primary" %>
</div>

app/views/surveys/stats.html.erb
<%= provide(:title, @survey.name) %>
>
<div class="center">

<h1><%= @survey.name %></h1>
	

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
    <tr>
    	<th>User</th>
    	<% @questions.each_with_index do |q, idx| %>
			<th>
			<!-- Link to modal -->
			<%= link_to "Q#{idx+1}.", "#", "data-toggle" => "modal", "data-target" => "#myModal#{q.id}" %>
			<%= render partial: "questions/display", locals: {q: q} %>
			</th>
    	<% end %>
    </tr
    </thead>
    <tbody>
    	<% @users.each do |uid| %>
    	<tr>
    		<th> <%= uid %> </th>
    		<% @questions.each do |q| %>
            <% answer = @answers[uid][q.id] %>
    		<% text =  (@answer_options[answer.id].collect { |ao| ao.answer_text } << answer.answer_text).join(" ") unless answer.nil? or @answer_options[answer.id].nil? %>
    			<% if q.question_type.id == @ta_type  %>
    				<td><%= link_to "View", "#", tabindex: 0, role: "button", "data-toggle"=>"popover", "data-placement"=>"right",title: "Question answer", "data-content"=>text %></td>
    			<% else %>
    			<td><%= text %></td>
    			<% end %>
    		<% end %>
    	</tr>
    	<% end %>

    		

    </tbody>
  </table>
  

<%= link_to "Export as CSV",  survey_stats_path(@survey, format: :csv), class: "btn btn-large btn-success"%>

</div>